In [17]:
#https://stackoverflow.com/questions/3172509/numpy-convert-categorical-string-arrays-to-an-integer-array
import numpy as np
import pandas as pd
a = np.array(['ac', 'b', 'c', 'ac', 'b', 'c'])
a_enc = pd.factorize(a)
print(a_enc[0])
print(a_enc[1])

def convert2num(category):
    import numpy as np
    import pandas as pd
    category = np.array(category)
    a_enc = pd.factorize(category)
    return a_enc[0]


convert2num(['ac', 'b', 'c', 'ac', 'b', 'c'])


[0 1 2 0 1 2]
['ac' 'b' 'c']


array([0, 1, 2, 0, 1, 2])

In [13]:
pd.factorize?

In [13]:
#https://stackoverflow.com/questions/3172509/numpy-convert-categorical-string-arrays-to-an-integer-array
import numpy as np
import pandas as pd
a = np.array(['c','ac', 'b', 'c', 'ac', 'b', 'c'])
#a = pd.Series(a)
a_enc = pd.Categorical(a)
print(a_enc.categories)
print(a_enc.codes)

Index(['ac', 'b', 'c'], dtype='object')
[2 0 1 2 0 1 2]


In [22]:
#Convert back from number to Char
dim = pd.Series(a_enc.categories.values)
print(dim)
sample = [2, 2, 2, 0, 1, 1, 1]
dim.take(sample)

0    ac
1     b
2     c
dtype: object


2     c
2     c
2     c
0    ac
1     b
1     b
1     b
dtype: object